### ISSUE TITLE
我在使用您的配置的时候，出现了问题，麻烦您看看谢谢了

### ISSUE THREAD

**Issue by ignition5** [QianSong1/wezterm-config#3]
我是ubuntu的环境，按照您说的方法，解压放在了对应的目录下，然后启动的时候报这个错误：

**Comment by QianSong1** [comment]
![image](https://github.com/QianSong1/wezterm-config/assets/101644710/fbe794e0-13ad-415d-a38e-f96dd15aa99e)
把linux平台相关的配置加上就可以

**Comment by piccheaszd** [comment]
![image](https://github.com/QianSong1/wezterm-config/assets/130952013/cfe63990-19f9-41f9-b68c-4eee611d7aa8)
您好，为什么我用最新的配置还是出现这个问题？配置文件中似乎是有设置平台的。我使用KevinSilvester的wezterm-config则是只能显示一个透明框。如果我开启vmware workstation的3d加速，此时是可以使用KevinSilvester的wezterm-config。但是开启wezterm需要十多秒。而且仍然不能使用您的配置。我看见你的neofetch中显示的也是vmware，请问您是怎么解决的呢
