### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by yexinghenglf** [QianSong1/wezterm-config#6]
请问怎么去解决这个问题
<img width="444" alt="PixPin_2024-05-11_15-45-49" src="https://github.com/QianSong1/wezterm-config/assets/144299841/ffdea243-a95d-4420-b1ca-a76ff141ef50">
meic每次启动都很难受

**Comment by QianSong1** [comment]
下载安装这些字体，https://github.com/ryanoasis/nerd-fonts/tree/v2.3.3/patched-fonts/Meslo/M/Regular/complete
